[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/idk/Documents/server/web_panel_server-main/artisan queue:work --sleep=3 --tries=3
numprocs=1
autostart=true
autorestart=true
user=idk
stdout_logfile=/home/idk/Documents/server/web_panel_server-main/storage/logs/worker.log
stderr_logfile=/home/idk/Documents/server/web_panel_server-main/storage/logs/worker-error.log