@extends('layouts.app',['title'=>$project->name])
@section('content')
<div class="page-head"><div><p class="eyebrow">Application detail</p><h1>{{ $project->name }}</h1><p class="muted">{{ $project->repository }} · {{ $project->branch }}</p></div><span class="badge {{ $project->status }}">{{ $project->status }}</span></div>
<div class="card"><div class="section-title">OPERATIONS</div><div class="actions"><form method="post" action="{{ route('projects.deploy',$project) }}">@csrf<button>DEPLOY AGAIN</button></form>@foreach(['start','stop','restart'] as $action)<form method="post" action="{{ route('projects.lifecycle',[$project,$action]) }}">@csrf<button class="secondary">{{ strtoupper($action) }}</button></form>@endforeach<a class="btn secondary" href="{{ route('projects.logs',$project) }}" target="_blank">CONTAINER LOGS</a><a class="btn secondary" href="https://{{ $project->primaryDomain->domain }}" target="_blank">OPEN SITE ↗</a><form method="post" action="{{ route('projects.destroy',$project) }}" onsubmit="return confirm('Hapus project ini? Container, source lokal, DNS Cloudflare, dan Tunnel ingress juga akan dihapus.')">@csrf @method('delete')<button class="danger">DELETE</button></form></div></div>
<div class="grid"><div class="card"><div class="section-title">CONFIGURATION</div><p><span class="muted">Runtime</span><br>{{ strtoupper($project->type) }}</p><p><span class="muted">Primary domain</span><br>{{ $project->primaryDomain->domain }}</p><p><span class="muted">Workspace</span><br><code>{{ $project->path() }}</code></p></div><div class="card"><div class="section-title">GITHUB WEBHOOK</div><p class="muted">Content type: application/json · event: push</p><code style="word-break:break-all">{{ route('webhooks.github',$project->webhook->uuid) }}</code>@if(session('webhook_secret'))<p><strong>Secret (ditampilkan sekali)</strong><br><code style="word-break:break-all">{{ session('webhook_secret') }}</code></p>@else<p class="muted">Secret tersimpan terenkripsi dan tidak ditampilkan kembali.</p>@endif<form method="post" action="{{ route('projects.webhook.rotate',$project) }}" onsubmit="return confirm('Secret lama akan langsung tidak berlaku. Lanjutkan?')">@csrf<button class="secondary">ROTATE SECRET</button></form></div></div>
<div class="card"><div class="section-title">ENVIRONMENT VARIABLES</div><p class="muted">Value terenkripsi dan tidak ditampilkan kembali. Key yang sama akan diperbarui.</p><form method="post" action="{{ route('projects.environment.store',$project) }}">@csrf<div class="grid"><label>Key<input name="key" required placeholder="APP_NAME"></label><label>Value<input type="password" name="value" required autocomplete="new-password"></label></div><label style="font-weight:400"><input style="display:inline;width:auto" type="checkbox" name="is_build_time" value="1"> Build-time (mis. VITE_*)</label><br><button>SAVE VARIABLE</button></form><div style="overflow:auto"><table><tbody>@forelse($project->environmentVariables as $variable)<tr><td><code>{{ $variable->key }}</code></td><td>••••••••</td><td>{{ $variable->is_build_time ? 'BUILD' : 'RUNTIME' }}</td><td><form method="post" action="{{ route('projects.environment.destroy',[$project,$variable]) }}">@csrf @method('delete')<button class="danger">REMOVE</button></form></td></tr>@empty<tr><td>Belum ada variable.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="section-title">DEPLOYMENT HISTORY</div><div style="overflow:auto"><table><thead><tr><th>ID</th><th>Trigger</th><th>Status</th><th>Commit</th><th>Timestamp</th></tr></thead><tbody>@forelse($project->deployments as $d)<tr><td><a href="{{ route('deployments.show',$d) }}">#{{ $d->id }}</a></td><td>{{ strtoupper($d->trigger) }}</td><td><span class="badge {{ $d->status }}">{{ $d->status }}</span></td><td><code>{{ $d->commit_sha ? substr($d->commit_sha,0,8) : '—' }}</code></td><td>{{ $d->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="5">Belum ada deploy.</td></tr>@endforelse</tbody></table></div></div>
<style>.section-title{font-size:9px;letter-spacing:1.3px;color:#a8b3c1;margin-bottom:15px}</style>
@endsection
