@extends('layouts.app',['title'=>'Domains'])
@section('content')
<div class="page-head"><div><p class="eyebrow">Edge routing</p><h1>Domain Management</h1><p class="muted">Kelola hostname dan sertifikat TLS untuk seluruh aplikasi.</p></div></div>
<div class="grid" style="grid-template-columns:minmax(280px,.7fr) minmax(420px,1.3fr)">
<section class="card"><div class="card-title"><span>ADD HOSTNAME</span><span class="live">ACME ENABLED</span></div><form method="post" action="{{ route('domains.store') }}">@csrf<label>Application<select name="project_id" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></label><label>Domain<input name="domain" required placeholder="app.example.com"></label><button>＋ ADD DOMAIN</button></form><p class="muted" style="font-size:10px;margin-top:15px">Pastikan DNS A/AAAA sudah mengarah ke server. Sertifikat diterbitkan Traefik setelah redeploy.</p></section>
<section class="card"><div class="card-title"><span>ROUTING TABLE</span><span class="muted">{{ $projects->sum(fn($p)=>$p->domains->count()) }} HOSTNAMES</span></div><div style="overflow:auto"><table><thead><tr><th>Application</th><th>Hostname</th><th>TLS</th><th>Role</th><th></th></tr></thead><tbody>@forelse($projects as $project)@foreach($project->domains as $domain)<tr><td><a href="{{ route('projects.show',$project) }}">{{ $project->name }}</a></td><td><code>{{ $domain->domain }}</code></td><td><span class="badge succeeded">ENABLED</span></td><td>{{ $domain->is_primary ? 'PRIMARY' : 'ALIAS' }}</td><td>@unless($domain->is_primary)<form method="post" action="{{ route('domains.destroy',$domain) }}" onsubmit="return confirm('Hapus domain ini?')">@csrf @method('delete')<button class="danger">REMOVE</button></form>@endunless</td></tr>@endforeach @empty<tr><td colspan="5">Belum ada domain.</td></tr>@endforelse</tbody></table></div></section>
</div>
<style>.card-title{display:flex;justify-content:space-between;font-size:9px;letter-spacing:1.3px;color:#a8b3c1;margin-bottom:15px}.live{color:var(--green);font-size:8px}@media(max-width:800px){.grid{grid-template-columns:1fr!important}}</style>
@endsection
